# Generated by Django 2.2 on 2020-08-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200816_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'discounts'},
        ),
    ]
